-- Generated by scripts/gen-catalog.mjs — do not edit by hand.
-- Re-run this file in the Supabase SQL editor after changing collections.js.
begin;
insert into public.game_config (id, starting_wallet, daily_allowance, welcome_bonus, bank_rate, puzzle_small, puzzle_medium, puzzle_large)
  values (1, 60, 40.5, 20, 0.7, 5, 10, 15)
  on conflict (id) do update set starting_wallet = excluded.starting_wallet, daily_allowance = excluded.daily_allowance,
    welcome_bonus = excluded.welcome_bonus, bank_rate = excluded.bank_rate, puzzle_small = excluded.puzzle_small,
    puzzle_medium = excluded.puzzle_medium, puzzle_large = excluded.puzzle_large;
insert into public.series (id, price, secret_odds) values ('animal1', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('animal1-0', 'animal1', 26, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-1', 'animal1', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-2', 'animal1', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-3', 'animal1', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-4', 'animal1', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-5', 'animal1', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-6', 'animal1', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-7', 'animal1', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-8', 'animal1', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-9', 'animal1', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-10', 'animal1', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-11', 'animal1', 14, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal1-secret', 'animal1', 185, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('animal2', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('animal2-0', 'animal2', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-1', 'animal2', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-2', 'animal2', 18, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-3', 'animal2', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-4', 'animal2', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-5', 'animal2', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-6', 'animal2', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-7', 'animal2', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-8', 'animal2', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-9', 'animal2', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-10', 'animal2', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-11', 'animal2', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal2-secret', 'animal2', 165, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('animal3', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('animal3-0', 'animal3', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-1', 'animal3', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-2', 'animal3', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-3', 'animal3', 16, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-4', 'animal3', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-5', 'animal3', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-6', 'animal3', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-7', 'animal3', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-8', 'animal3', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-9', 'animal3', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-10', 'animal3', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-11', 'animal3', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('animal3-secret', 'animal3', 175, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('cat', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('cat-0', 'cat', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-1', 'cat', 15, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-2', 'cat', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-3', 'cat', 14, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-4', 'cat', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-5', 'cat', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-6', 'cat', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-7', 'cat', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-8', 'cat', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-9', 'cat', 16, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-10', 'cat', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-11', 'cat', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('cat-secret', 'cat', 220, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('dog', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('dog-0', 'dog', 15, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-1', 'dog', 16, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-2', 'dog', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-3', 'dog', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-4', 'dog', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-5', 'dog', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-6', 'dog', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-7', 'dog', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-8', 'dog', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-9', 'dog', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-10', 'dog', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-11', 'dog', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-12', 'dog', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('dog-secret', 'dog', 190, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('bugs', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('bugs-0', 'bugs', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-1', 'bugs', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-2', 'bugs', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-3', 'bugs', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-4', 'bugs', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-5', 'bugs', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-6', 'bugs', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-7', 'bugs', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-8', 'bugs', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-9', 'bugs', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-10', 'bugs', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-11', 'bugs', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('bugs-secret', 'bugs', 150, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('fruit', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('fruit-0', 'fruit', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-1', 'fruit', 24, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-2', 'fruit', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-3', 'fruit', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-4', 'fruit', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-5', 'fruit', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-6', 'fruit', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-7', 'fruit', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-8', 'fruit', 15, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-9', 'fruit', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-10', 'fruit', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-11', 'fruit', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('fruit-secret', 'fruit', 150, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('vegetable', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('vegetable-0', 'vegetable', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-1', 'vegetable', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-2', 'vegetable', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-3', 'vegetable', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-4', 'vegetable', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-5', 'vegetable', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-6', 'vegetable', 14, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-7', 'vegetable', 6, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-8', 'vegetable', 6, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-9', 'vegetable', 6, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-10', 'vegetable', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-11', 'vegetable', 6, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('vegetable-secret', 'vegetable', 140, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('marine', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('marine-0', 'marine', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-1', 'marine', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-2', 'marine', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-3', 'marine', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-4', 'marine', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-5', 'marine', 14, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-6', 'marine', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-7', 'marine', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-8', 'marine', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-9', 'marine', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-10', 'marine', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-11', 'marine', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('marine-secret', 'marine', 155, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('flower', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('flower-0', 'flower', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-1', 'flower', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-2', 'flower', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-3', 'flower', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-4', 'flower', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-5', 'flower', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-6', 'flower', 28, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-7', 'flower', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-8', 'flower', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-9', 'flower', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-10', 'flower', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-11', 'flower', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('flower-secret', 'flower', 160, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('sweets', 12.95, 144)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('sweets-0', 'sweets', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-1', 'sweets', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-2', 'sweets', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-3', 'sweets', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-4', 'sweets', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-5', 'sweets', 20, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-6', 'sweets', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-7', 'sweets', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-8', 'sweets', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-9', 'sweets', 8, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-10', 'sweets', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-11', 'sweets', 7, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('sweets-secret', 'sweets', 170, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('halloween', 14.95, 72)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('halloween-0', 'halloween', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-1', 'halloween', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-2', 'halloween', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-3', 'halloween', 14, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-4', 'halloween', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-5', 'halloween', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('halloween-secret', 'halloween', 200, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('christmas', 14.95, 72)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('christmas-0', 'christmas', 15, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-1', 'christmas', 13, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-2', 'christmas', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-3', 'christmas', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-4', 'christmas', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-5', 'christmas', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('christmas-secret', 'christmas', 230, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('valentine', 14.95, 72)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('valentine-0', 'valentine', 16, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-1', 'valentine', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-2', 'valentine', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-3', 'valentine', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-4', 'valentine', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-5', 'valentine', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('valentine-secret', 'valentine', 210, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.series (id, price, secret_odds) values ('easter', 14.95, 72)
  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;
insert into public.figures (id, series_id, value, secret) values ('easter-0', 'easter', 15, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-1', 'easter', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-2', 'easter', 11, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-3', 'easter', 9, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-4', 'easter', 10, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-5', 'easter', 12, false)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
insert into public.figures (id, series_id, value, secret) values ('easter-secret', 'easter', 190, true)
  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;
delete from public.wheel_prizes;
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash5', 'cash', 5, null, 300, 0);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('fig1', 'figures', null, 1, 200, 1);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash10', 'cash', 10, null, 220, 2);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash20', 'cash', 20, null, 120, 3);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('fig2', 'figures', null, 2, 50, 4);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash15', 'cash', 15, null, 55, 5);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash50', 'cash', 50, null, 30, 6);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('fig3', 'figures', null, 3, 15, 7);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('cash100', 'cash', 100, null, 8, 8);
insert into public.wheel_prizes (key, kind, amount, count, weight, sort) values ('secret', 'secret', null, 1, 2, 9);
commit;
