// Generates supabase/catalog.sql from src/data/collections.js so the server
// knows every series, figure, price and value. Run: npm run gen:catalog
import { writeFileSync } from 'node:fs'
import { SERIES, DAILY_ALLOWANCE, STARTING_WALLET, WELCOME_BONUS, BANK_RATE, PUZZLE_REWARDS, PUZZLE_DAILY_LIMIT } from '../src/data/collections.js'

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const lines = [
  '-- Generated by scripts/gen-catalog.mjs — do not edit by hand.',
  '-- Re-run this file in the Supabase SQL editor after changing collections.js.',
  'begin;',
  `insert into public.game_config (id, starting_wallet, daily_allowance, welcome_bonus, bank_rate, puzzle_small, puzzle_medium, puzzle_large, puzzle_daily_limit)`,
  `  values (1, ${STARTING_WALLET}, ${DAILY_ALLOWANCE}, ${WELCOME_BONUS}, ${BANK_RATE}, ${PUZZLE_REWARDS.small}, ${PUZZLE_REWARDS.medium}, ${PUZZLE_REWARDS.large}, ${PUZZLE_DAILY_LIMIT})`,
  '  on conflict (id) do update set starting_wallet = excluded.starting_wallet, daily_allowance = excluded.daily_allowance,',
  '    welcome_bonus = excluded.welcome_bonus, bank_rate = excluded.bank_rate, puzzle_small = excluded.puzzle_small,',
  '    puzzle_medium = excluded.puzzle_medium, puzzle_large = excluded.puzzle_large, puzzle_daily_limit = excluded.puzzle_daily_limit;',
]
for (const s of SERIES) {
  lines.push(
    `insert into public.series (id, price, secret_odds) values (${q(s.id)}, ${s.price}, ${s.odds})`,
    '  on conflict (id) do update set price = excluded.price, secret_odds = excluded.secret_odds;',
  )
  for (const f of [...s.figures, s.secret]) {
    lines.push(
      `insert into public.figures (id, series_id, value, secret) values (${q(f.id)}, ${q(s.id)}, ${f.value}, ${f.secret})`,
      '  on conflict (id) do update set series_id = excluded.series_id, value = excluded.value, secret = excluded.secret;',
    )
  }
}
lines.push('commit;', '')
writeFileSync(new URL('../supabase/catalog.sql', import.meta.url), lines.join('\n'))
console.log(`Wrote catalog for ${SERIES.length} series`)
